/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ColorPicker: typeof import('./src/components/ColorPicker.vue')['default']
    DragUpload: typeof import('./src/components/DragUpload.vue')['default']
    FormSelect: typeof import('./src/components/FormSelect.vue')['default']
    PanelContainer: typeof import('./src/components/PanelContainer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectableMenu: typeof import('./src/components/SelectableMenu.vue')['default']
  }
}
