import type { NodeStickerGroup } from '@/@types'

export default <NodeStickerGroup[]>[
  {
    name: '商务',
    list: [
      { url: '/svg/business/-.svg', width: 100, height: 100 },
      { url: '/svg/business/-_1.svg', width: 100, height: 100 },
      { url: '/svg/business/-_10.svg', width: 100, height: 100 },
      { url: '/svg/business/-_11.svg', width: 100, height: 100 },
      { url: '/svg/business/-_12.svg', width: 100, height: 100 },
      { url: '/svg/business/-_13.svg', width: 100, height: 100 },
      { url: '/svg/business/-_14.svg', width: 100, height: 100 },
      { url: '/svg/business/-_15.svg', width: 100, height: 100 },
      { url: '/svg/business/-_16.svg', width: 100, height: 100 },
      { url: '/svg/business/-_17.svg', width: 100, height: 100 },
      { url: '/svg/business/-_18.svg', width: 100, height: 100 },
      { url: '/svg/business/-_2.svg', width: 100, height: 100 },
      { url: '/svg/business/-_3.svg', width: 100, height: 100 },
      { url: '/svg/business/-_4.svg', width: 100, height: 100 },
      { url: '/svg/business/-_5.svg', width: 100, height: 100 },
      { url: '/svg/business/-_6.svg', width: 100, height: 100 },
      { url: '/svg/business/-_7.svg', width: 100, height: 100 },
      { url: '/svg/business/-_8.svg', width: 100, height: 100 },
      { url: '/svg/business/-_9.svg', width: 100, height: 100 },
      { url: '/svg/business/OAxitong.svg', width: 100, height: 100 },
      { url: '/svg/business/changyongziyuan.svg', width: 100, height: 100 },
      { url: '/svg/business/chuchashenpi.svg', width: 100, height: 100 },
      { url: '/svg/business/fanwendengji.svg', width: 100, height: 100 },
      { url: '/svg/business/feizhengshiwendengji.svg', width: 100, height: 100 },
      { url: '/svg/business/gongwenjiaohuan.svg', width: 100, height: 100 },
      { url: '/svg/business/gongzuohuibao.svg', width: 100, height: 100 },
      { url: '/svg/business/gudingzichan.svg', width: 100, height: 100 },
      { url: '/svg/business/huiyiguanli.svg', width: 100, height: 100 },
      { url: '/svg/business/huiyiyuding.svg', width: 100, height: 100 },
      { url: '/svg/business/kaoqinguanli.svg', width: 100, height: 100 },
      { url: '/svg/business/qingxiujiashenqing.svg', width: 100, height: 100 },
      { url: '/svg/business/sannianjihua.svg', width: 100, height: 100 },
      { url: '/svg/business/tongzhifabu.svg', width: 100, height: 100 },
      { url: '/svg/business/xiangmuguanli.svg', width: 100, height: 100 },
      { url: '/svg/business/xinxitougao.svg', width: 100, height: 100 },
      { url: '/svg/business/zhishichanquan.svg', width: 100, height: 100 },
      { url: '/svg/business/zhongxindongtaifabu.svg', width: 100, height: 100 },
      { url: '/svg/business/zongheshenpi.svg', width: 100, height: 100 },
    ],
  },
  {
    name: '教育',
    list: [
      { url: '/svg/education/a-1-shilibiao.svg', width: 100, height: 100 },
      { url: '/svg/education/a-10-yiliaoxiang.svg', width: 100, height: 100 },
      { url: '/svg/education/a-11-yiyongweishengzhi.svg', width: 100, height: 100 },
      { url: '/svg/education/a-12-huxi.svg', width: 100, height: 100 },
      { url: '/svg/education/a-13-xiguan.svg', width: 100, height: 100 },
      { url: '/svg/education/a-14-zhutingqi.svg', width: 100, height: 100 },
      { url: '/svg/education/a-15-bingdu.svg', width: 100, height: 100 },
      { url: '/svg/education/a-16-yiyuan.svg', width: 100, height: 100 },
      { url: '/svg/education/a-17-zhusheqi.svg', width: 100, height: 100 },
      { url: '/svg/education/a-18-xiguan.svg', width: 100, height: 100 },
      { url: '/svg/education/a-19-guaizhang.svg', width: 100, height: 100 },
      { url: '/svg/education/a-2-kouzhao.svg', width: 100, height: 100 },
      { url: '/svg/education/a-20-shuye.svg', width: 100, height: 100 },
      { url: '/svg/education/a-3-chuangkoutie.svg', width: 100, height: 100 },
      { url: '/svg/education/a-4-lunyi.svg', width: 100, height: 100 },
      { url: '/svg/education/a-5-mianqian.svg', width: 100, height: 100 },
      { url: '/svg/education/a-6-jiancebi.svg', width: 100, height: 100 },
      { url: '/svg/education/a-7-xinzang.svg', width: 100, height: 100 },
      { url: '/svg/education/a-8-DNA.svg', width: 100, height: 100 },
      { url: '/svg/education/a-9-tizhongcheng.svg', width: 100, height: 100 },
      { url: '/svg/education/a-bitong1.svg', width: 100, height: 100 },
      { url: '/svg/education/a-shu2.svg', width: 100, height: 100 },
      { url: '/svg/education/a-shu4.svg', width: 100, height: 100 },
      { url: '/svg/education/a-shu5.svg', width: 100, height: 100 },
      { url: '/svg/education/a-shuben2.svg', width: 100, height: 100 },
      { url: '/svg/education/a-shuben3.svg', width: 100, height: 100 },
      { url: '/svg/education/a-shuben4.svg', width: 100, height: 100 },
      { url: '/svg/education/a-xueshimao1.svg', width: 100, height: 100 },
      { url: '/svg/education/baichui.svg', width: 100, height: 100 },
      { url: '/svg/education/bijiben.svg', width: 100, height: 100 },
      { url: '/svg/education/bitong.svg', width: 100, height: 100 },
      { url: '/svg/education/chizi.svg', width: 100, height: 100 },
      { url: '/svg/education/chongdian.svg', width: 100, height: 100 },
      { url: '/svg/education/citie.svg', width: 100, height: 100 },
      { url: '/svg/education/daima.svg', width: 100, height: 100 },
      { url: '/svg/education/deng.svg', width: 100, height: 100 },
      { url: '/svg/education/dianliushiyan.svg', width: 100, height: 100 },
      { url: '/svg/education/diqiu.svg', width: 100, height: 100 },
      { url: '/svg/education/diqiuyi.svg', width: 100, height: 100 },
      { url: '/svg/education/fanyi.svg', width: 100, height: 100 },
      { url: '/svg/education/gongwenbao.svg', width: 100, height: 100 },
      { url: '/svg/education/heiban.svg', width: 100, height: 100 },
      { url: '/svg/education/huiyi.svg', width: 100, height: 100 },
      { url: '/svg/education/jiangbei.svg', width: 100, height: 100 },
      { url: '/svg/education/jiaoxuelou.svg', width: 100, height: 100 },
      { url: '/svg/education/jinpai.svg', width: 100, height: 100 },
      { url: '/svg/education/jisuan.svg', width: 100, height: 100 },
      { url: '/svg/education/jisuanqi.svg', width: 100, height: 100 },
      { url: '/svg/education/naozhong.svg', width: 100, height: 100 },
      { url: '/svg/education/qianbi.svg', width: 100, height: 100 },
      { url: '/svg/education/sepan.svg', width: 100, height: 100 },
      { url: '/svg/education/shiyan.svg', width: 100, height: 100 },
      { url: '/svg/education/shouji.svg', width: 100, height: 100 },
      { url: '/svg/education/shuben.svg', width: 100, height: 100 },
      { url: '/svg/education/shuxie.svg', width: 100, height: 100 },
      { url: '/svg/education/sousuo.svg', width: 100, height: 100 },
      { url: '/svg/education/suanpan.svg', width: 100, height: 100 },
      { url: '/svg/education/tianping.svg', width: 100, height: 100 },
      { url: '/svg/education/tingzhenqi.svg', width: 100, height: 100 },
      { url: '/svg/education/tiyu.svg', width: 100, height: 100 },
      { url: '/svg/education/wenjian.svg', width: 100, height: 100 },
      { url: '/svg/education/xianweijing.svg', width: 100, height: 100 },
      { url: '/svg/education/xiaoheiban.svg', width: 100, height: 100 },
      { url: '/svg/education/xiezizhuo.svg', width: 100, height: 100 },
      { url: '/svg/education/xueshimao.svg', width: 100, height: 100 },
      { url: '/svg/education/yuanpan.svg', width: 100, height: 100 },
    ],
  },
  {
    name: '节日',
    list: [
      { url: '/svg/festival/celianggongju.svg', width: 100, height: 100 },
      { url: '/svg/festival/chunjie.svg', width: 100, height: 100 },
      { url: '/svg/festival/duanwujie.svg', width: 100, height: 100 },
      { url: '/svg/festival/ertongjie.svg', width: 100, height: 100 },
      { url: '/svg/festival/fuqinjie.svg', width: 100, height: 100 },
      { url: '/svg/festival/ganenjie.svg', width: 100, height: 100 },
      { url: '/svg/festival/gongju.svg', width: 100, height: 100 },
      { url: '/svg/festival/hushijie.svg', width: 100, height: 100 },
      { url: '/svg/festival/jiaoshijie.svg', width: 100, height: 100 },
      { url: '/svg/festival/laodongjie.svg', width: 100, height: 100 },
      { url: '/svg/festival/muqinjie.svg', width: 100, height: 100 },
      { url: '/svg/festival/nvshengjie.svg', width: 100, height: 100 },
      { url: '/svg/festival/qingrenjie.svg', width: 100, height: 100 },
      { url: '/svg/festival/qixi.svg', width: 100, height: 100 },
      { url: '/svg/festival/shengdanjie.svg', width: 100, height: 100 },
      { url: '/svg/festival/shuang.svg', width: 100, height: 100 },
      { url: '/svg/festival/yuandan.svg', width: 100, height: 100 },
      { url: '/svg/festival/yuanxiaojie.svg', width: 100, height: 100 },
      { url: '/svg/festival/zhongqiujie.svg', width: 100, height: 100 },
      { url: '/svg/festival/zhongyangjie.svg', width: 100, height: 100 },
    ],
  },
  {
    name: '食物',
    list: [
      { url: '/svg/food/binggan.svg', width: 100, height: 100 },
      { url: '/svg/food/binggun.svg', width: 100, height: 100 },
      { url: '/svg/food/bingqilin.svg', width: 100, height: 100 },
      { url: '/svg/food/boluo.svg', width: 100, height: 100 },
      { url: '/svg/food/caomei.svg', width: 100, height: 100 },
      { url: '/svg/food/celianggongju.svg', width: 100, height: 100 },
      { url: '/svg/food/chengzi.svg', width: 100, height: 100 },
      { url: '/svg/food/dangao.svg', width: 100, height: 100 },
      { url: '/svg/food/fanqiejiang.svg', width: 100, height: 100 },
      { url: '/svg/food/gongju.svg', width: 100, height: 100 },
      { url: '/svg/food/hanbao.svg', width: 100, height: 100 },
      { url: '/svg/food/jiandan.svg', width: 100, height: 100 },
      { url: '/svg/food/kafeibei.svg', width: 100, height: 100 },
      { url: '/svg/food/lajiao.svg', width: 100, height: 100 },
      { url: '/svg/food/naixi.svg', width: 100, height: 100 },
      { url: '/svg/food/niunai.svg', width: 100, height: 100 },
      { url: '/svg/food/pingguo.svg', width: 100, height: 100 },
      { url: '/svg/food/pisa.svg', width: 100, height: 100 },
      { url: '/svg/food/putao.svg', width: 100, height: 100 },
      { url: '/svg/food/quqi.svg', width: 100, height: 100 },
      { url: '/svg/food/regou.svg', width: 100, height: 100 },
      { url: '/svg/food/shutiao.svg', width: 100, height: 100 },
      { url: '/svg/food/sudaqishui.svg', width: 100, height: 100 },
      { url: '/svg/food/taozi.svg', width: 100, height: 100 },
      { url: '/svg/food/tiantianquan.svg', width: 100, height: 100 },
      { url: '/svg/food/xiangjiao.svg', width: 100, height: 100 },
      { url: '/svg/food/xigua.svg', width: 100, height: 100 },
      { url: '/svg/food/xilanhua.svg', width: 100, height: 100 },
      { url: '/svg/food/yingtao.svg', width: 100, height: 100 },
      { url: '/svg/food/yumi.svg', width: 100, height: 100 },
    ],
  },
  {
    name: '医疗',
    list: [
      { url: '/svg/medicine/a-1-shilibiao.svg', width: 100, height: 100 },
      { url: '/svg/medicine/a-10-yiliaoxiang.svg', width: 100, height: 100 },
      { url: '/svg/medicine/a-11-yiyongweishengzhi.svg', width: 100, height: 100 },
      { url: '/svg/medicine/a-12-huxi.svg', width: 100, height: 100 },
      { url: '/svg/medicine/a-13-xiguan.svg', width: 100, height: 100 },
      { url: '/svg/medicine/a-14-zhutingqi.svg', width: 100, height: 100 },
      { url: '/svg/medicine/a-15-bingdu.svg', width: 100, height: 100 },
      { url: '/svg/medicine/a-16-yiyuan.svg', width: 100, height: 100 },
      { url: '/svg/medicine/a-17-zhusheqi.svg', width: 100, height: 100 },
      { url: '/svg/medicine/a-18-xiguan.svg', width: 100, height: 100 },
      { url: '/svg/medicine/a-19-guaizhang.svg', width: 100, height: 100 },
      { url: '/svg/medicine/a-2-kouzhao.svg', width: 100, height: 100 },
      { url: '/svg/medicine/a-20-shuye.svg', width: 100, height: 100 },
      { url: '/svg/medicine/a-3-chuangkoutie.svg', width: 100, height: 100 },
      { url: '/svg/medicine/a-4-lunyi.svg', width: 100, height: 100 },
      { url: '/svg/medicine/a-5-mianqian.svg', width: 100, height: 100 },
      { url: '/svg/medicine/a-6-jiancebi.svg', width: 100, height: 100 },
      { url: '/svg/medicine/a-7-xinzang.svg', width: 100, height: 100 },
      { url: '/svg/medicine/a-8-DNA.svg', width: 100, height: 100 },
      { url: '/svg/medicine/a-9-tizhongcheng.svg', width: 100, height: 100 },
    ],
  },
  {
    name: '工具',
    list: [
      { url: '/svg/tools/gaizhui.svg', width: 100, height: 100 },
      { url: '/svg/tools/ziyuan_1.svg', width: 100, height: 100 },
      { url: '/svg/tools/ziyuan_2.svg', width: 100, height: 100 },
      { url: '/svg/tools/ziyuan_3.svg', width: 100, height: 100 },
      { url: '/svg/tools/ziyuan_4.svg', width: 100, height: 100 },
      { url: '/svg/tools/ziyuan_5.svg', width: 100, height: 100 },
      { url: '/svg/tools/ziyuan_6.svg', width: 100, height: 100 },
      { url: '/svg/tools/ziyuan_7.svg', width: 100, height: 100 },
      { url: '/svg/tools/ziyuan_8.svg', width: 100, height: 100 },
      { url: '/svg/tools/ziyuan_9.svg', width: 100, height: 100 },
      { url: '/svg/tools/ziyuan_10.svg', width: 100, height: 100 },
      { url: '/svg/tools/ziyuan_11.svg', width: 100, height: 100 },
    ],
  },
  {
    name: '旅行',
    list: [
      { url: '/svg/travel/banshouli.svg', width: 100, height: 100 },
      { url: '/svg/travel/chuhangshijian.svg', width: 100, height: 100 },
      { url: '/svg/travel/ditu.svg', width: 100, height: 100 },
      { url: '/svg/travel/fengjing.svg', width: 100, height: 100 },
      { url: '/svg/travel/gonglve.svg', width: 100, height: 100 },
      { url: '/svg/travel/hangli.svg', width: 100, height: 100 },
      { url: '/svg/travel/huafei.svg', width: 100, height: 100 },
      { url: '/svg/travel/jipiao.svg', width: 100, height: 100 },
      { url: '/svg/travel/jiudian.svg', width: 100, height: 100 },
      { url: '/svg/travel/lvban.svg', width: 100, height: 100 },
      { url: '/svg/travel/meishi.svg', width: 100, height: 100 },
      { url: '/svg/travel/menpiao.svg', width: 100, height: 100 },
      { url: '/svg/travel/paishe.svg', width: 100, height: 100 },
      { url: '/svg/travel/qianzheng.svg', width: 100, height: 100 },
      { url: '/svg/travel/shangdian.svg', width: 100, height: 100 },
      { url: '/svg/travel/tianqi.svg', width: 100, height: 100 },
      { url: '/svg/travel/youlechangsuo.svg', width: 100, height: 100 },
      { url: '/svg/travel/yuyanfanyi.svg', width: 100, height: 100 },
      { url: '/svg/travel/zhuyishixiang.svg', width: 100, height: 100 },
      { url: '/svg/travel/zuche.svg', width: 100, height: 100 },
    ],
  },
]
